name: Setup Pages
on:
  push:
      branches:
      - main
jobs:
  setup-pages:
      permissions:
        contents: write
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: oven-sh/setup-bun@v2
        - name: Install dependencies
          run: npm install
        - name: build
          run: npm run build
        - uses: stefanzweifel/git-auto-commit-action@v5
          

